theme = "kaolin-dark"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
rulers = [80]
true-color = true
gutters = [
  "diagnostics",
  "spacer",
  "line-numbers",
  "spacer",
  "diff",
]

[editor.smart-tab]
enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# [editor.statusline]
# left = ["mode", "spinner", "version-control", "file-name"]

